name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write # required for OIDC (Trusted Publishing)
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No token needed; OIDC is used
          print-hash: true
